### ISSUE TITLE
Weekly Review (2017/08/07)

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-example#127]
A list of issues assigned to nobody.
# ansible-role-employees

* [ ] issue 29: [User account that keeps changing](https://github.com/reallyenglish/ansible-role-employees/issues/29)

# ansible-role-example

* [ ] issue 125: [docs/Procedures/Maintaining_Repository does not describe the `Require pull request reviews before merging`](https://github.com/reallyenglish/ansible-role-example/issues/125)
* [ ] issue 123: [lack of reference about release versioning](https://github.com/reallyenglish/ansible-role-example/issues/123)
* [x] issue 119: [Weekly Review (2017/07/31)](https://github.com/reallyenglish/ansible-role-example/issues/119)
* [ ] issue 95: [Create local box repository](https://github.com/reallyenglish/ansible-role-example/issues/95)
* [ ] issue 33: [Update sysutils/ansible in Jenkins slave to 2.2.0 or newer](https://github.com/reallyenglish/ansible-role-example/issues/33)
* [ ] issue 32: [Jenkins test is slow](https://github.com/reallyenglish/ansible-role-example/issues/32)

# ansible-role-hadoop-namenode

* [x] issue 14: [[bugfix] Modernize](https://github.com/reallyenglish/ansible-role-hadoop-namenode/pull/14)

# ansible-role-jenkins-slave

* [ ] issue 17: [generating/distributing authorized_keys should not be done in the role](https://github.com/reallyenglish/ansible-role-jenkins-slave/issues/17)

# ansible-role-nfs-client

* [ ] issue 3: [NFSv4 is not supported](https://github.com/reallyenglish/ansible-role-nfs-client/issues/3)

# ansible-role-nfs-server

* [ ] issue 5: [NFSv4 is not supported](https://github.com/reallyenglish/ansible-role-nfs-server/issues/5)
* [ ] issue 3: [CentOS is not supported by the role](https://github.com/reallyenglish/ansible-role-nfs-server/issues/3)

# ansible-role-nsd

* [ ] issue 24: [the role does not support external data](https://github.com/reallyenglish/ansible-role-nsd/issues/24)

# ansible-role-postfix

* [ ] issue 9: [tables in postfix_tables are not validated](https://github.com/reallyenglish/ansible-role-postfix/issues/9)

# ansible-role-rabbitmq

* [ ] issue 14: [Mirrored queues should be tested in integration test](https://github.com/reallyenglish/ansible-role-rabbitmq/issues/14)

# ansible-role-unbound

* [x] issue 41: [the role does not use `reallyenglish.x509-certificate`](https://github.com/reallyenglish/ansible-role-unbound/issues/41)
* [ ] issue 27: [the role does not support chroot(2) in Ubuntu, and CentOS](https://github.com/reallyenglish/ansible-role-unbound/issues/27)

# ansible-role-virtual-interface

* [ ] issue 22: [introducing state attribute](https://github.com/reallyenglish/ansible-role-virtual-interface/issues/22)
* [ ] issue 18: [bridge0 needs to be configured after vether0](https://github.com/reallyenglish/ansible-role-virtual-interface/issues/18)
