### ISSUE TITLE
Weekly Review (2016/10/22)

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-example#22]
A list of issues assigned to nobody.
# ansible-role-debug

* [x] issue 8: [Create a task to dump all variables to a file](https://github.com/reallyenglish/ansible-role-debug/issues/8)
* [x] issue 3: [Create ansible-role-epel](https://github.com/reallyenglish/ansible-role-debug/issues/3)
* [x] issue 2: [Support centos](https://github.com/reallyenglish/ansible-role-debug/issues/2)

# ansible-role-editors

* [x] issue 2: [fall back to empty string if not defined](https://github.com/reallyenglish/ansible-role-editors/pull/2)

# ansible-role-example

* [x] issue 18: [there is no automated way to know all unassigned issues in all ansible-role-*](https://github.com/reallyenglish/ansible-role-example/issues/18)

# ansible-role-freebsd-repos

* [x] issue 6: [README does not describe all variables](https://github.com/reallyenglish/ansible-role-freebsd-repos/issues/6)

# ansible-role-monit

* [x] issue 13: [document how validation works](https://github.com/reallyenglish/ansible-role-monit/issues/13)
* [x] issue 4: [validate fragments](https://github.com/reallyenglish/ansible-role-monit/issues/4)
* [x] issue 1: [alert should be supported](https://github.com/reallyenglish/ansible-role-monit/issues/1)

# ansible-role-nsd

* [x] issue 13: [support centos](https://github.com/reallyenglish/ansible-role-nsd/issues/13)
* [x] issue 10: [fix a pending issue, "should_not be_listening.on('192.168.133.101').with('tcp')"](https://github.com/reallyenglish/ansible-role-nsd/issues/10)

# ansible-role-ospfd

* [x] issue 9: [README does not describe all variables](https://github.com/reallyenglish/ansible-role-ospfd/issues/9)

# ansible-role-pf

* [x] issue 4: [create an integration test](https://github.com/reallyenglish/ansible-role-pf/issues/4)

# ansible-role-redhat-repo

* [x] issue 4: [when tests take longer than 600 sec, #verify action fails](https://github.com/reallyenglish/ansible-role-redhat-repo/issues/4)

# ansible-role-resolver

* [x] issue 5: [the role does not support centos](https://github.com/reallyenglish/ansible-role-resolver/issues/5)
* [x] issue 4: [the role does not support ubuntu](https://github.com/reallyenglish/ansible-role-resolver/issues/4)

# ansible-role-root

* [x] issue 1: [OpenBSD fails because `getent passwd root` does not display password field](https://github.com/reallyenglish/ansible-role-root/issues/1)

# ansible-role-rsyslog

* [x] issue 9: [the README does not show variables for each platform](https://github.com/reallyenglish/ansible-role-rsyslog/issues/9)

# ansible-role-unbound

* [x] issue 8: [does not have an integration test](https://github.com/reallyenglish/ansible-role-unbound/issues/8)
* [x] issue 6: [support centos](https://github.com/reallyenglish/ansible-role-unbound/issues/6)
* [x] issue 2: [stub-zone is not supported](https://github.com/reallyenglish/ansible-role-unbound/issues/2)

# ansible-role-virtual-interface

* [x] issue 6: [the role does not support centos](https://github.com/reallyenglish/ansible-role-virtual-interface/issues/6)
* [x] issue 5: [the role does not support Ubuntu](https://github.com/reallyenglish/ansible-role-virtual-interface/issues/5)
* [x] issue 4: [the role does not support FreeBSD](https://github.com/reallyenglish/ansible-role-virtual-interface/issues/4)

**Comment by trombik** [comment]
all issues have been assigned.
