### ISSUE TITLE
Weekly Review (2016/10/31)

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-example#25]
A list of issues assigned to nobody.

# ansible-role-debug
- [x] issue 12: [bind(2) would probably fail in CentOS](https://github.com/reallyenglish/ansible-role-debug/issues/12)

# ansible-role-example
- [x] issue 24: [When an wiki page is updated, the update is not notified to repository members](https://github.com/reallyenglish/ansible-role-example/issues/24)

# ansible-role-nsd
- [x] issue 16: [Issue 13](https://github.com/reallyenglish/ansible-role-nsd/pull/16)
- [x] issue 15: [SELinux policy for CentOS is broken](https://github.com/reallyenglish/ansible-role-nsd/issues/15)

# ansible-role-ntpd
- [x] issue 8: [CentOS - the role is not correcty applied when libselinux-python is not installed](https://github.com/reallyenglish/ansible-role-ntpd/issues/8)

# ansible-role-root
- [x] issue 7: [kitchen failed "The requested URL returned error: 404 Not Found"](https://github.com/reallyenglish/ansible-role-root/issues/7)

# ansible-role-unbound
- [x] issue 12: [does not handle chroot](https://github.com/reallyenglish/ansible-role-unbound/issues/12)

**Comment by trombik** [comment]
all issues have been assigned
