### ISSUE TITLE
Weekly Review (2016/11/07)

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-example#27]
A list of issues assigned to nobody.
# ansible-role-dhclient

* [x] issue 4: [an example in unit test is in "pending" state](https://github.com/reallyenglish/ansible-role-dhclient/issues/4)

# ansible-role-nsd

* [x] issue 18: [tasks create certs and keys does not have `validate`](https://github.com/reallyenglish/ansible-role-nsd/issues/18)

# ansible-role-sshd

* [x] issue 10: [sshd is not installed by the role on CentOS and Ubuntu](https://github.com/reallyenglish/ansible-role-sshd/issues/10)

**Comment by trombik** [comment]
all assigned
