### ISSUE TITLE
Weekly Review (2016/11/28)

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-example#30]
A list of issues assigned to nobody.
# ansible-role-fluentd

* [x] issue 9: [the role does not have an integration test](https://github.com/reallyenglish/ansible-role-fluentd/issues/9)
* [x] issue 8: [the role supports FreeBSD only](https://github.com/reallyenglish/ansible-role-fluentd/issues/8)

# ansible-role-kibana

* [ ] issue 8: [the role has never been released](https://github.com/reallyenglish/ansible-role-kibana/issues/8)
* [ ] issue 7: [the role has not been tested by qansible](https://github.com/reallyenglish/ansible-role-kibana/issues/7)

# ansible-role-nsd

* [ ] issue 24: [the role does not support external data](https://github.com/reallyenglish/ansible-role-nsd/issues/24)
* [ ] issue 22: [missing test case when chroot is enabled](https://github.com/reallyenglish/ansible-role-nsd/issues/22)
* [x] issue 21: [nsd.conf is not validated](https://github.com/reallyenglish/ansible-role-nsd/issues/21)

**Comment by trombik** [comment]
time out, close
