### ISSUE TITLE
Weekly Review (2016/12/26)

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-example#31]
A list of issues assigned to nobody.
# ansible-role-elasticsearch

* [x] issue 8: [the role install and configures Java](https://github.com/reallyenglish/ansible-role-elasticsearch/issues/8)

# ansible-role-example

* [x] issue 30: [Weekly Review (2016/11/28)](https://github.com/reallyenglish/ansible-role-example/issues/30)

# ansible-role-fluentd

* [x] issue 14: [the role does not support OpenBSD](https://github.com/reallyenglish/ansible-role-fluentd/issues/14)

# ansible-role-freebsd-repos

* [ ] issue 9: [the role does not support multiple package URLs](https://github.com/reallyenglish/ansible-role-freebsd-repos/issues/9)

# ansible-role-java

* [x] issue 8: [Release 1.0.0](https://github.com/reallyenglish/ansible-role-java/pull/8)
* [ ] issue 7: [fix linuxism in specinfra](https://github.com/reallyenglish/ansible-role-java/issues/7)
* [x] issue 6: [roles that depend on Java need updates](https://github.com/reallyenglish/ansible-role-java/issues/6)

# ansible-role-kibana

* [x] issue 8: [the role has never been released](https://github.com/reallyenglish/ansible-role-kibana/issues/8)
* [x] issue 7: [the role has not been tested by qansible](https://github.com/reallyenglish/ansible-role-kibana/issues/7)

# ansible-role-logstash

* [x] issue 12: [the role does not support OpenBSD](https://github.com/reallyenglish/ansible-role-logstash/issues/12)
* [x] issue 11: [the role does not support CentOS](https://github.com/reallyenglish/ansible-role-logstash/issues/11)
* [x] issue 10: [the role does not support SSL](https://github.com/reallyenglish/ansible-role-logstash/issues/10)
* [x] issue 9: [create or fork ansible-role-java](https://github.com/reallyenglish/ansible-role-logstash/issues/9)
* [ ] issue 7: [fix linuxism in specinfra](https://github.com/reallyenglish/ansible-role-logstash/issues/7)
* [ ] issue 6: [needs to update root certificates](https://github.com/reallyenglish/ansible-role-logstash/issues/6)

# ansible-role-nsd

* [ ] issue 24: [the role does not support external data](https://github.com/reallyenglish/ansible-role-nsd/issues/24)
* [ ] issue 22: [missing test case when chroot is enabled](https://github.com/reallyenglish/ansible-role-nsd/issues/22)

# ansible-role-redis

* [x] issue 10: [README.md is out-of-date](https://github.com/reallyenglish/ansible-role-redis/issues/10)
* [x] issue 7: [the role does not support read-only slave](https://github.com/reallyenglish/ansible-role-redis/issues/7)

**Comment by trombik** [comment]
remaining issues were brought to the next weekly review
