### ISSUE TITLE
Weekly Review (2017/01/19)

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-example#39]
A list of issues assigned to nobody.
# ansible-role-cbsd

* [ ] issue 2: [support VIMAGE](https://github.com/reallyenglish/ansible-role-cbsd/issues/2)

# ansible-role-editors

* [x] issue 6: [Can't find vim--no_x11 on OpenBSD 6.0](https://github.com/reallyenglish/ansible-role-editors/issues/6)

# ansible-role-example

* [ ] issue 37: [Using proxy in Jenkins environment](https://github.com/reallyenglish/ansible-role-example/issues/37)
* [x] issue 36: [Creating more Jenkins slaves](https://github.com/reallyenglish/ansible-role-example/issues/36)
* [x] issue 35: [Make Jenkins stages parallel (dividing kitchen test stage and integration tests to multiple jobs so that multiple Jenkins slave can perform tasks in parallel)](https://github.com/reallyenglish/ansible-role-example/issues/35)
* [x] issue 34: [Jenkins slave is not managed by ansible](https://github.com/reallyenglish/ansible-role-example/issues/34)
* [ ] issue 33: [Update sysutils/ansible in Jenkins slave to 2.2.0 or newer](https://github.com/reallyenglish/ansible-role-example/issues/33)
* [ ] issue 32: [Jenkins test is slow](https://github.com/reallyenglish/ansible-role-example/issues/32)
* [x] issue 31: [Weekly Review (2016/12/26)](https://github.com/reallyenglish/ansible-role-example/issues/31)

# ansible-role-freebsd-repos

* [ ] issue 9: [the role does not support multiple package URLs](https://github.com/reallyenglish/ansible-role-freebsd-repos/issues/9)

# ansible-role-java

* [x] issue 13: [Java package version for OpenBSD is hard-coded](https://github.com/reallyenglish/ansible-role-java/issues/13)
* [x] issue 9: [the role does not set wxallowed mount(8) option on OpenBSD](https://github.com/reallyenglish/ansible-role-java/issues/9)
* [x] issue 7: [fix linuxism in specinfra](https://github.com/reallyenglish/ansible-role-java/issues/7)

# ansible-role-jenkins-master

* [x] issue 4: [the role does not support OpenBSD](https://github.com/reallyenglish/ansible-role-jenkins-master/issues/4)

# ansible-role-logstash

* [x] issue 7: [fix linuxism in specinfra](https://github.com/reallyenglish/ansible-role-logstash/issues/7)
* [ ] issue 6: [needs to update root certificates](https://github.com/reallyenglish/ansible-role-logstash/issues/6)

# ansible-role-nsd

* [ ] issue 24: [the role does not support external data](https://github.com/reallyenglish/ansible-role-nsd/issues/24)
* [x] issue 22: [missing test case when chroot is enabled](https://github.com/reallyenglish/ansible-role-nsd/issues/22)

# ansible-role-postfix

* [ ] issue 13: [Update ansible that supports OpenBSD's "pkgname%branch" syntax](https://github.com/reallyenglish/ansible-role-postfix/issues/13)
* [x] issue 11: [the role does not validate main.cf or master.cf ](https://github.com/reallyenglish/ansible-role-postfix/issues/11)
* [ ] issue 7: [periodic tasks for sendmail are not disabled in FreeBSD](https://github.com/reallyenglish/ansible-role-postfix/issues/7)
* [ ] issue 4: [the role does not have an integration test](https://github.com/reallyenglish/ansible-role-postfix/issues/4)

# ansible-role-poudriere

* [ ] issue 8: [Create minimal ports tree for the test](https://github.com/reallyenglish/ansible-role-poudriere/issues/8)

**Comment by trombik** [comment]
close the weekly review in the last week.
