### ISSUE TITLE
Weekly Review (2017/01/30)

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-example#40]
A list of issues assigned to nobody.
# ansible-role-cbsd

* [ ] issue 2: [support VIMAGE](https://github.com/reallyenglish/ansible-role-cbsd/issues/2)

# ansible-role-editors

* [ ] issue 8: [update emacs package name for openbsd, change variable names](https://github.com/reallyenglish/ansible-role-editors/pull/8)

# ansible-role-example

* [ ] issue 37: [Using proxy in Jenkins environment](https://github.com/reallyenglish/ansible-role-example/issues/37)
* [ ] issue 33: [Update sysutils/ansible in Jenkins slave to 2.2.0 or newer](https://github.com/reallyenglish/ansible-role-example/issues/33)
* [ ] issue 32: [Jenkins test is slow](https://github.com/reallyenglish/ansible-role-example/issues/32)
* [x] issue 41: [deprecated ansible-role-init/ansible-role-qa in doc/*](https://github.com/reallyenglish/ansible-role-example/issues/41)

# ansible-role-freebsd-repos

* [ ] issue 9: [the role does not support multiple package URLs](https://github.com/reallyenglish/ansible-role-freebsd-repos/issues/9)

# ansible-role-java

* [x] issue 21: [reallyenglish.apt-repo is installed in the freebsd box ignoring conditional dependencies](https://github.com/reallyenglish/ansible-role-java/issues/21)
* [ ] issue 13: [Java package version for OpenBSD is hard-coded](https://github.com/reallyenglish/ansible-role-java/issues/13)

# ansible-role-logstash

* [ ] issue 6: [needs to update root certificates](https://github.com/reallyenglish/ansible-role-logstash/issues/6)

# ansible-role-nsd

* [ ] issue 24: [the role does not support external data](https://github.com/reallyenglish/ansible-role-nsd/issues/24)

# ansible-role-postfix

* [ ] issue 13: [Update ansible that supports OpenBSD's "pkgname%branch" syntax](https://github.com/reallyenglish/ansible-role-postfix/issues/13)
* [ ] issue 7: [periodic tasks for sendmail are not disabled in FreeBSD](https://github.com/reallyenglish/ansible-role-postfix/issues/7)
* [ ] issue 4: [the role does not have an integration test](https://github.com/reallyenglish/ansible-role-postfix/issues/4)

# ansible-role-poudriere

* [ ] issue 8: [Create minimal ports tree for the test](https://github.com/reallyenglish/ansible-role-poudriere/issues/8)

# ansible-role-virtual-interface

* [x] issue 19: [In which role do we configure physical interface?](https://github.com/reallyenglish/ansible-role-virtual-interface/issues/19)
* [ ] issue 18: [bridge0 needs to be configured after vether0](https://github.com/reallyenglish/ansible-role-virtual-interface/issues/18)

**Comment by trombik** [comment]
close for the next review
