### ISSUE TITLE
Weekly Review (2017/02/06)

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-example#47]
A list of issues assigned to nobody.
# ansible-role-cbsd

* [ ] issue 2: [support VIMAGE](https://github.com/reallyenglish/ansible-role-cbsd/issues/2)

# ansible-role-editors

* [ ] issue 8: [update emacs package name for openbsd, change variable names](https://github.com/reallyenglish/ansible-role-editors/pull/8)

# ansible-role-elasticsearch

* [ ] issue 19: [ansible warns when importing the role](https://github.com/reallyenglish/ansible-role-elasticsearch/issues/19)

# ansible-role-example

* [ ] issue 46: [no document describing how to configure github repository](https://github.com/reallyenglish/ansible-role-example/issues/46)
* [ ] issue 45: [docs/Releasing.md does not mention which version we should start](https://github.com/reallyenglish/ansible-role-example/issues/45)
* [x] issue 40: [Weekly Review (2017/01/30)](https://github.com/reallyenglish/ansible-role-example/issues/40)
* [ ] issue 37: [Using proxy in Jenkins environment](https://github.com/reallyenglish/ansible-role-example/issues/37)
* [ ] issue 33: [Update sysutils/ansible in Jenkins slave to 2.2.0 or newer](https://github.com/reallyenglish/ansible-role-example/issues/33)
* [ ] issue 32: [Jenkins test is slow](https://github.com/reallyenglish/ansible-role-example/issues/32)

# ansible-role-freebsd-repos

* [ ] issue 9: [the role does not support multiple package URLs](https://github.com/reallyenglish/ansible-role-freebsd-repos/issues/9)

# ansible-role-java

* [ ] issue 13: [Java package version for OpenBSD is hard-coded](https://github.com/reallyenglish/ansible-role-java/issues/13)

# ansible-role-logstash

* [ ] issue 20: [master branch is broken](https://github.com/reallyenglish/ansible-role-logstash/issues/20)
* [ ] issue 6: [needs to update root certificates](https://github.com/reallyenglish/ansible-role-logstash/issues/6)

# ansible-role-nsd

* [ ] issue 24: [the role does not support external data](https://github.com/reallyenglish/ansible-role-nsd/issues/24)

# ansible-role-postfix

* [ ] issue 13: [Update ansible that supports OpenBSD's "pkgname%branch" syntax](https://github.com/reallyenglish/ansible-role-postfix/issues/13)
* [ ] issue 7: [periodic tasks for sendmail are not disabled in FreeBSD](https://github.com/reallyenglish/ansible-role-postfix/issues/7)
* [ ] issue 4: [the role does not have an integration test](https://github.com/reallyenglish/ansible-role-postfix/issues/4)

# ansible-role-poudriere

* [ ] issue 8: [Create minimal ports tree for the test](https://github.com/reallyenglish/ansible-role-poudriere/issues/8)

# ansible-role-vagrant

* [ ] issue 3: [the role does not support CentOS](https://github.com/reallyenglish/ansible-role-vagrant/issues/3)

# ansible-role-virtual-interface

* [x] issue 22: [introducing state attribute](https://github.com/reallyenglish/ansible-role-virtual-interface/issues/22)
* [x] issue 18: [bridge0 needs to be configured after vether0](https://github.com/reallyenglish/ansible-role-virtual-interface/issues/18)

**Comment by trombik** [comment]
close for the next weekly review
