### ISSUE TITLE
Weekly Review (2017/02/20)

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-example#63]
A list of issues assigned to nobody.
# ansible-role-cbsd

* [ ] issue 2: [support VIMAGE](https://github.com/reallyenglish/ansible-role-cbsd/issues/2)

# ansible-role-editors

* [ ] issue 8: [update emacs package name for openbsd, change variable names](https://github.com/reallyenglish/ansible-role-editors/pull/8)

# ansible-role-employees

* [ ] issue 29: [User account that keeps changing](https://github.com/reallyenglish/ansible-role-employees/issues/29)

# ansible-role-example

* [x] issue 60: [create standard rubocop.yml](https://github.com/reallyenglish/ansible-role-example/issues/60)
* [x] issue 59: [document a guide to write tests](https://github.com/reallyenglish/ansible-role-example/issues/59)
* [x] issue 58: [no coding style is documented](https://github.com/reallyenglish/ansible-role-example/issues/58)
* [x] issue 50: [Weekly Review (2017/02/13)](https://github.com/reallyenglish/ansible-role-example/issues/50)
* [x] issue 48: [document a policy to name variables under `var/`](https://github.com/reallyenglish/ansible-role-example/issues/48)
* [ ] issue 37: [Using proxy in Jenkins environment](https://github.com/reallyenglish/ansible-role-example/issues/37)
* [ ] issue 33: [Update sysutils/ansible in Jenkins slave to 2.2.0 or newer](https://github.com/reallyenglish/ansible-role-example/issues/33)
* [ ] issue 32: [Jenkins test is slow](https://github.com/reallyenglish/ansible-role-example/issues/32)

# ansible-role-freebsd-repos

* [ ] issue 9: [the role does not support multiple package URLs](https://github.com/reallyenglish/ansible-role-freebsd-repos/issues/9)

# ansible-role-java

* [ ] issue 13: [Java package version for OpenBSD is hard-coded](https://github.com/reallyenglish/ansible-role-java/issues/13)

# ansible-role-logstash

* [ ] issue 20: [master branch is broken](https://github.com/reallyenglish/ansible-role-logstash/issues/20)
* [ ] issue 6: [needs to update root certificates](https://github.com/reallyenglish/ansible-role-logstash/issues/6)

# ansible-role-nsd

* [ ] issue 29: [old format is still used in `meta/main.yml`](https://github.com/reallyenglish/ansible-role-nsd/issues/29)
* [ ] issue 28: [Issue 26 27](https://github.com/reallyenglish/ansible-role-nsd/pull/28)
* [ ] issue 24: [the role does not support external data](https://github.com/reallyenglish/ansible-role-nsd/issues/24)

# ansible-role-postfix

* [ ] issue 13: [Update ansible that supports OpenBSD's "pkgname%branch" syntax](https://github.com/reallyenglish/ansible-role-postfix/issues/13)
* [ ] issue 7: [periodic tasks for sendmail are not disabled in FreeBSD](https://github.com/reallyenglish/ansible-role-postfix/issues/7)
* [ ] issue 4: [the role does not have an integration test](https://github.com/reallyenglish/ansible-role-postfix/issues/4)

# ansible-role-poudriere

* [x] issue 8: [Create minimal ports tree for the test](https://github.com/reallyenglish/ansible-role-poudriere/issues/8)

# ansible-role-unbound

* [ ] issue 21: ["Register unbound version" task is skipped in check-mode](https://github.com/reallyenglish/ansible-role-unbound/issues/21)

**Comment by trombik** [comment]
close for the next review
